Add Readme
CraftAcademy/gigafood pull request #40
Opened 2017-09-19 08:51 UTC by faraznaeem

### PT-Link https://www.pivotaltracker.com/story/show/150942456 ###

## Add Readme to gigafood ##

2017-09-19 13:32 UTC, tochman commented
Pull from upstream, run `bundle` and push to this branch to fix the failing tests @faraznaeem

2017-09-19 13:38 UTC, faraznaeem commented
getting merge conflicts, can I safely remove the gemfile.lock and then pull from upstream?

2017-09-19 14:17 UTC, tochman requested changes

2017-09-19 14:17 UTC, tochman commented on README.md
> +GigaFood is a catering businessthat creates organic plant-based vegan dishes that are marvelous to eat, high in nutrition, good for your health and sustainable for the planet.
Typo. ;-)

2017-09-20 07:55 UTC, faraznaeem commented on README.md
> +GigaFood is a catering businessthat creates organic plant-based vegan dishes that are marvelous to eat, high in nutrition, good for your health and sustainable for the planet.
Done :)

2017-09-20 08:05 UTC, tochman approved these changes

2017-09-20 08:05 UTC, merged