Validate required fields
CraftAcademy/gigafood pull request #41
Opened 2017-09-20 05:21 UTC by j0sv

## PT: https://www.pivotaltracker.com/story/show/151126573 ##

- Add required to input fields required before user submit an order.

2017-09-20 05:32 UTC, tochman requested changes
In the model, please use 'validates_presence_of' validation. Just setting the fields to required does not cut it.

2017-09-20 05:48 UTC, j0sv commented
The address and other information don't exist then the instance is created. The validation needs to be made in the controller if it should be made on server side also.

2017-09-20 07:08 UTC, tochman requested changes
Please add specs for the validations

2017-09-20 07:08 UTC, tochman commented on app/models/order.rb
> +  validates :delivery_date,       presence: true, :if => :submitted?
Old hash syntax 😜

2017-09-20 13:18 UTC, tochman requested changes
I still don't see any specs for the validations and the new methods on the Order model.

2017-09-20 13:18 UTC, tochman commented on app/controllers/orders_controller.rb
> +          #flash[:notice] = "#{dish.name} was successfully added to order!"
If you remove this line then the entire if statement makes no sense. Or does it? Perhaps use a modifier:
```
flash[:alert] = 'Item not added, try again!' unless @order.add(dish, dish.price, dish_value.to_i)
```
but I'm not sure if I like it...

2017-09-20 13:18 UTC, tochman commented on app/controllers/orders_controller.rb
> +      flash[:alert] = 'Error then saving order!'
Error WHEN saving order. Do we have a test for this `else`block?  Is there a use case`

2017-09-21 10:18 UTC, tochman commented
Merge conflicts need to be resolved and unit specs added. Not mergeable in this state.

2017-09-21 13:30 UTC, tochman requested changes
There are comments in the code. Please remove them. Can't see the relevant CSS classes for the flash. Am I missing something? I will pull down the branch to take a closer look at the unit specs. Can't see why you are updating the subject before testing the validations.

2017-09-21 13:53 UTC, j0sv commented
There aren't any css classes. Removing the class from the HTML element.

2017-09-21 14:27 UTC, faraznaeem approved these changes

2017-09-21 14:28 UTC, merged