adds sendgrid to production config
CraftAcademy/gigafood pull request #51
Opened 2017-09-22 10:59 UTC by caressahh

### PT STORY https://www.pivotaltracker.com/n/projects/2104405/stories/151123839 ###

- Added sendgrid gem

- add sendgrid config for production enviornment

2017-09-22 11:00 UTC, tochman requested changes

2017-09-22 11:00 UTC, tochman commented on config/environments/production.rb
> +    :enable_starttls_auto => true
All of this is the old hash syntax

2017-09-22 11:02 UTC, caressahh commented on config/environments/production.rb
> +    :enable_starttls_auto => true
WOOPS! fixed.

2017-09-23 11:52 UTC, tochman approved these changes
We need to add the credentials to Heroku.

2017-09-23 11:52 UTC, merged